[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.venv",
  "python310Packages.pip",
  "git",
  "git-lfs"
]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  ". /app/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = ". /app/venv/bin/activate && python app.py"
