[phases.setup]
nixPkgs = ["git" "git-lfs" "python310"]

[phases.install]
cmds = [
  "git lfs install",
  "git lfs pull",
  "python3.10 -m ensurepip",
  "python3.10 -m pip install --upgrade pip",
  "python3.10 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.10 app.py"
