[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "git", "git-lfs"]

[phases.install]
cmds = [
  "git lfs install",
  "git lfs pull || true",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python app.py"
