[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel", "git", "git-lfs"]

[phases.install]
cmds = [
  "git lfs install",
  "git lfs pull || true",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python3 app.py"
